# Generated by Django 5.2.8 on 2025-12-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Yard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('time', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('staff', models.ManyToManyField(related_name='work_day', to='tracker.employee')),
                ('yards_cut', models.ManyToManyField(related_name='work_day', to='tracker.yard')),
            ],
        ),
    ]
